### ISSUE TITLE
Is it Possible to get "inner temperature" from Lock-in-Thermography?

### ISSUE THREAD

**Issue by bemoregt** [isuthermography/greensinversion#1]
Hi, @sdh4 

I know that Lock-in-Thermography is the algorith to finding inner defects.
Then,
Is it Possible to get "inner temperature" from Lock-in-Thermography?,
by means of FFT calculation ?

Thanks in advance.

from @bemoregt.

**Comment by sdh4** [comment]
Out of scope for this project (pulse thermography not lock-in). But in general, no. From thermal camera measurements you can get surface temperature but that doesn't tell you subsurface temperature, and the FFT is not a magical algorithm that would create such information.
